version: '3.3'

services:
  app:
    image: 'foodie-angular-app'
    build: ..\..\Laboratorio2\Foodie
    ports:
        - 8000:80
  express:
    build: '.'
    ports:
        - "3000:3000"
    links:
        - redisDB
        - mongo
  mongo:
    image: mongo
    ports:
        - "27017:27017"
  redisDB:
    image: redis
    ports:
        - "6379:6379"
  